# Nama workflow untuk identifikasi di GitHub Actions
name: Ternak Pro CI/CD Pipeline

# Pemicu untuk menjalankan workflow
on:
  push:
    branches:
      - main  # Jalankan saat ada push ke branch main
  pull_request:
    branches:
      - main  # Jalankan untuk pull request yang menargetkan main

jobs:
  build_and_test:
    name: Build & Test
    runs-on: ubuntu-latest
    
    # Environment variables untuk Android SDK
    env:
      ANDROID_HOME: /usr/local/lib/android/sdk
      ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
      PATH: $PATH:/usr/local/lib/android/sdk/cmdline-tools/latest/bin:/usr/local/lib/android/sdk/platform-tools

    steps:
      # Langkah 1: Checkout dengan setup tar terlebih dahulu
      - name: Install tar utility
        run: sudo apt-get update && sudo apt-get install -y tar
      
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Untuk mendapatkan seluruh history git

      # Langkah 2: Setup Android SDK
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Langkah 3: Setup JDK
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Langkah 4: Setup Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.5'
          channel: 'stable'
          cache: true

      # Langkah-langkah berikutnya tetap sama...
      - name: Show Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze --fatal-infos

      - name: Run tests
        run: flutter test
        
      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Install Android NDK
        run: |
          ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin/sdkmanager --install "ndk;29.0.13599879"
          yes | ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk

  # Job untuk deploy (opsional, bisa diaktifkan nanti)
  # Saat ini dikomentari agar tidak berjalan
  # deploy:
  #   name: Deploy to Store
  #   runs-on: ubuntu-latest
  #   needs: build_and_test # Hanya berjalan jika job build_and_test sukses
  #   steps:
  #     - name: Download APK artifact
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: release-apk
  #
  #     - name: Deploy to Google Play
  #       # Anda bisa menggunakan action seperti 'r0adkll/upload-google-play@v1'
  #       # atau skrip custom untuk deploy.
  #       run: echo "Deploying to Google Play Store..."
  #       # Contoh penggunaan action (memerlukan setup credentials):
  #       # uses: r0adkll/upload-google-play@v1
  #       # with:
  #       #   serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT }}
  #       #   packageName: com.your.package.name
  #       #   releaseFiles: app-release.apk
  #       #   track: internal